name: concurrency

on:
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]

# 追いコミット入ったら実行中のワークフローをキャンセルして最新のコミットでやり直す設定
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - run: sleep 60
